version: 2.1

executors:
  amd64:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
  arm64:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: arm.medium

platforms: &platforms
  - amd64
  - arm64

node_versions: &node_versions
  - "14"
  - "16"

workflows:
  build:
    jobs:
      - build:
          context: docker-publishing
          matrix:
            parameters:
              executor: *platforms
              node_version: *node_versions
      - manifest:
          context: docker-publishing
          requires: [ build ]
          matrix:
            parameters:
              node_version: *node_versions
          filters:
            branches:
              only: [ main ]

  nightly:
    jobs:
      - build:
          context: docker-publishing
          matrix:
            parameters:
              executor: *platforms
              node_version: *node_versions
      - manifest:
          context: docker-publishing
          requires: [ build ]
          matrix:
            parameters:
              node_version: *node_versions
          filters:
            branches:
              only: [ main ]
    triggers:
      - schedule:
          # Scheduled build for 2am AEST nightly.
          cron: "0 15 * * *"
          filters:
            branches:
              only: [ main ]

jobs:
  build:
    parameters:
      executor:
        type: string
      node_version:
        type: string
    executor: << parameters.executor >>
    steps:
      - checkout
      - run:
          name: Build, Test and Release
          command: |
            SHA1_VERSION="v2-$(git rev-parse --short HEAD)"
            make build ARCH=<< parameters.executor >> NODE_VERSION=<< parameters.node_version >> VERSION_TAG=v2-latest
            make build ARCH=<< parameters.executor >> NODE_VERSION=<< parameters.node_version >> VERSION_TAG=${SHA1_VERSION}
      - when:
          condition:
            equal: ["main", << pipeline.git.branch >> ]
          steps:
            - run:
                name: "Push image"
                command: |
                  echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                  SHA1_VERSION="v2-$(git rev-parse --short HEAD)"
                  make push ARCH=<< parameters.executor >> NODE_VERSION=<< parameters.node_version >> VERSION_TAG=v2-latest
                  make push ARCH=<< parameters.executor >> NODE_VERSION=<< parameters.node_version >> VERSION_TAG=${SHA1_VERSION}
  manifest:
    docker:
      - image: cimg/base:2022.02
    parameters:
      node_version:
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.7
      - run:
          name: Push Manifest
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            SHA1_VERSION="v2-$(git rev-parse --short HEAD)"
            make manifest NODE_VERSION=<< parameters.node_version >> VERSION_TAG=v2-latest
            make manifest NODE_VERSION=<< parameters.node_version >> VERSION_TAG=${SHA1_VERSION}
